baseURL = 'https://chikit.ca/'
languageCode = 'en-US'
title = "Chikit Portfolio"
theme = 'mana'

[outputs]
  home = ['HTML', 'JSON']

[params]
  description = 'Cool guy and even cooler stuff'
  heroTitleLine1 = 'Portfolio'
  heroTitleLine2 = 'Video Games and Marketing'

[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[menus.main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 20

[[menus.main]]
  name = "Tags"
  pageRef = "/tags"
  weight = 30

  [params.social]
  github = "https://github.com/superoak1"
  linkedin = "https://www.linkedin.com/in/phillip-chung-2ba51883/"
  email = "phillip.chung5@gmail.com"

  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
