baseURL = 'https://chikit.ca/'
languageCode = 'en-US'
title = "Chikit's Portfolio"
theme = 'mana'

[outputs]
  home = ['HTML', 'JSON']

[params]
  description = 'Cool guy and even cooler stuff'
  heroTitleLine1 = 'Portfolio'
  heroTitleLine2 = 'Video Games and Marketing'

[params.social]
  github = "https://github.com/superoak1"
  linkedin = "https://www.linkedin.com/in/phillip-chung-2ba51883/"
  email = "phillip.chung5@gmail.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menus.main]]
  name = "Video Games"
  url = "/games/"
  weight = 10

[[menus.main]]
  name = "Marketing"
  url = "/marketing/"
  weight = 20

[[menus.main]]
  name = "Misc"
  url = "/misc/"
  weight = 25

[[menus.main]]
  name = "Tags"
  pageRef = "/tags"
  weight = 30